### PR TITLE
fix: outdated xud peer address

### PR DESCRIPTION
**Pull request by reliveyy**

### CODE REVIEW

**Review by kilrau — APPROVED** [review]

**Review by michael1011 — COMMENTED** [review]
Hold on for a minute. Which port is exposed on the instance? We need to double check that. I think that the local xud connects fine to the cloud instance on port `8885`, doesn't it?

**Comment by reliveyy** [comment]
> Hold on for a minute. Which port is exposed on the instance? We need to double check that. I think that the local xud connects fine to the cloud instance on port `8885`, doesn't it?

The xud launching with "simnet" will auto connect to `02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6@xud1.simnet.exchangeunion.com:28885`. So I guess the script connect command fails. And why the native xud-simnet still connects to the xud1 is becuase of the xud auto connecting.

**Comment by reliveyy** [comment]
> Which port is exposed on the instance?

Just checked it. The port 8885 is not listening.

**Comment by kilrau** [comment]
It *has* to be 28885, otherwise consfusing af.. this is simnet. Please check that it is 28885 and only 28885.

**Comment by reliveyy** [comment]
> It _has_ to be 28885, otherwise consfusing af.. this is simnet. Please check on xud1.simnet.exchangeunion.com that it is 28885 listening and only 28885.

Checked. 28885 ONLY.

**Comment by kilrau** [comment]
Good to go? @michael1011

**Review by michael1011 — APPROVED** [review]
Good to go!

**Pull request merged**
